# Copyright (C) 2026 AERA Recovery Project contributors
# SPDX-License-Identifier: GPL-3.0-or-later

DEVICE_PATH := device/xiaomi/myron

# Project identity and adaptive UI metrics for the 1200x2608 panel.
AERA_MAINTAINER := haohao3001
AERA_SCREEN_H := 2374
AERA_STATUS_H := 141
AERA_STATUS_INDENT_LEFT := 56
AERA_STATUS_INDENT_RIGHT := 56
AERA_HIDE_NOTCH := 1
AERA_CLOCK_POS := 1
AERA_ALLOW_DISABLE_NAVBAR := 0
AERA_OPTIONS_LIST_NUM := 6

# Flashlight
AERA_USE_GREEN_LED := 0
AERA_FLASHLIGHT_ENABLE := 1
AERA_FL_PATH1 := /sys/class/leds/yellow:flash-0

# Partition and format handling
AERA_DYNAMIC_FULL_SIZE := 14495514624
AERA_DISPLAY_FORMAT_FILESYSTEMS_DEBUG_INFO := 1
AERA_ENABLE_ALL_PARTITION_TOOLS := 1
AERA_USE_AIDL_BOOT_CONTROL := 1
AERA_USE_DMCTL := 1
AERA_FORCE_DATA_FORMAT_F2FS := 1
AERA_FORCE_CASEFOLDING := 1
AERA_UNBIND_SDCARD_F2FS := 1
AERA_BIND_MOUNT_SDCARD_ON_FORMAT := 1
AERA_UNMOUNT_SDCARDS_BEFORE_REBOOT := 1
AERA_WIPE_METADATA_AFTER_DATAFORMAT := 1
AERA_WORKAROUND_BACKUP_BUG := 1

# Kernel and recovery behavior
AERA_FORCE_PREBUILT_KERNEL := 1
AERA_AB_DEVICE_WITH_RECOVERY_PARTITION := 1
AERA_NO_RELOAD_AFTER_DECRYPTION := 1
AERA_NO_TREBLE_COMPATIBILITY_CHECK := 1
AERA_USE_LZ4_COMPRESSION := 1
AERA_ENABLE_WLAN := 1
AERA_ENABLE_FRP_ADDON := 1

# This ROM family may leave an already populated /data/media/0 without a
# directory-level fscrypt policy. The CE key still unlocks its contents; allow
# AERA to complete the post-decrypt /sdcard and MTP hand-off in that exact case.
AERA_ALLOW_POPULATED_MEDIA_WITHOUT_POLICY := 1
PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
    ro.aera.allow_nonempty_media=$(AERA_ALLOW_POPULATED_MEDIA_WITHOUT_POLICY)
